@echo off
REM Descarga las imagenes a .\images\ usando curl
if not exist images mkdir images
curl -s -o "images\logo_fibrefab.png" "https://www.ds3comunicaciones.com/FibreFab/images/logo_fibrefab.png"
curl -s -o "images\logo_andrew.jpg" "https://www.ds3comunicaciones.com/andrew/images/logo_andrew.jpg"
curl -s -o "images\ALFA_logo1.gif" "https://www.ds3comunicaciones.com/belden/images/ALFA_logo1.gif"
curl -s -o "images\Belden-Logo-93x15.jpg" "https://www.ds3comunicaciones.com/belden/images/Belden-Logo-93x15.jpg"
curl -s -o "images\D-Link_Logo-100x26.jpg" "https://www.ds3comunicaciones.com/belden/images/D-Link_Logo-100x26.jpg"
curl -s -o "images\airlivelogo.gif" "https://www.ds3comunicaciones.com/belden/images/airlivelogo.gif"
curl -s -o "images\amp_logo2-91x20.jpg" "https://www.ds3comunicaciones.com/belden/images/amp_logo2-91x20.jpg"
curl -s -o "images\amphenol_logo-100x21.jpg" "https://www.ds3comunicaciones.com/belden/images/amphenol_logo-100x21.jpg"
curl -s -o "images\dixon_logo-100x19.jpg" "https://www.ds3comunicaciones.com/belden/images/dixon_logo-100x19.jpg"
curl -s -o "images\mikrotik_logo-100x24.png" "https://www.ds3comunicaciones.com/belden/images/mikrotik_logo-100x24.png"
curl -s -o "images\tp-link_logo-100x13.jpg" "https://www.ds3comunicaciones.com/belden/images/tp-link_logo-100x13.jpg"
curl -s -o "images\trendnet_logo-100x20.jpg" "https://www.ds3comunicaciones.com/belden/images/trendnet_logo-100x20.jpg"
curl -s -o "images\ubnt_logo-100x47.png" "https://www.ds3comunicaciones.com/belden/images/ubnt_logo-100x47.png"
curl -s -o "images\logo-cisco.gif" "https://www.ds3comunicaciones.com/cisco/images/logo-cisco.gif"
curl -s -o "images\dahua_logo.jpg" "https://www.ds3comunicaciones.com/dahua/images/dahua_logo.jpg"
curl -s -o "images\lanpro_logo.jpg" "https://www.ds3comunicaciones.com/lanpro/images/lanpro_logo.jpg"
curl -s -o "images\Logo1.jpg" "https://www.ds3comunicaciones.com/mikrotik/images/Logo1.jpg"
curl -s -o "images\panduit_logo.jpg" "https://www.ds3comunicaciones.com/panduit/images/panduit_logo.jpg"
curl -s -o "images\satra.JPG" "https://www.ds3comunicaciones.com/satra/images/satra.JPG"
curl -s -o "images\siemon_logo1.GIF" "https://www.ds3comunicaciones.com/siemon/images/siemon_logo1.GIF"
curl -s -o "images\lcom_logo-100x23.jpg" "https://www.ds3comunicaciones.com/sitebuilder/images/lcom_logo-100x23.jpg"
curl -s -o "images\1427254-4-1.jpg" "https://www.ds3comunicaciones.com/AMP/images/1427254-4-1.jpg"
curl -s -o "images\1859218-2.jpg" "https://www.ds3comunicaciones.com/AMP/images/1859218-2.jpg"
curl -s -o "images\219585-2_front.jpg" "https://www.ds3comunicaciones.com/AMP/images/219585-2_front.jpg"
curl -s -o "images\6-1427200-4-1.jpg" "https://www.ds3comunicaciones.com/AMP/images/6-1427200-4-1.jpg"
curl -s -o "images\Caja.jpg" "https://www.ds3comunicaciones.com/AMP/images/Caja.jpg"
echo Listo. Imagenes en .\images\